name: Build Reframe360XL (Linux)

on: 
  workflow_dispatch: # This adds the "Run workflow" button in the Actions tab
  push:
    branches: [ "main" ] # Or "master"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CUDA 13.2
        uses: Jimver/cuda-toolkit@v0.2.35
        with:
          cuda: '13.2.0'
          method: 'network'

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ocl-icd-opencl-dev opencl-headers

      - name: Download OpenFX SDK
        run: |
          git clone https://github.com openfx-sdk

      - name: Compile with Makefile
        run: |
          export CUDAPATH=$CUDA_PATH
          # Point the build to the local SDK folder we just downloaded
          export BMDOFXDEVPATH=$GITHUB_WORKSPACE/openfx-sdk
          make clean
          make


      - name: Compile with Makefile
        run: |
          # Use the environment variable set by the cuda-toolkit action
          export CUDAPATH=$CUDA_PATH
          make clean
          make

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Reframe360XL-Linux
          path: Reframe360XL.so
